### ISSUE TITLE
Camera pose estimate

### ISSUE THREAD

**Issue by Tversmissen** [qcr/gtsam-quadrics#10]
Hi,

@nikosuenderhauf @btalb 

Thanks for the nice work!

I wanted to use QuadricSLAM to estimate the camera pose.

I used the realsense.py example as a starting point.
However, the camera pose I got at the end of the while loop in realsense.py (line 544) is the same as the estimate by the openCV lib earlier (line 453) .

Does this repository provide methods to estimate the camera pose by the quadrics alone or improve the openCV camera pose ?
I don't know if I understood correctly, but I thought your paper mentioned that quadricslam was correcting for odometry errors.

Thanks.

**Comment by btalb** [comment]
Sorry about the long delay @Tversmissen ; this repository has been under some work.

1. Camera pose estimation can be performed if you have reliable object detection and data association, which can be challenging in real world scenarios
2. Examples have been moved to our new [QuadricSLAM repo](https://github.com/qcr/quadricslam), which explores how object detections can be used to form quadric estimates in a SLAM-style system

Hope that helps. Feel free to re-open if you have further questions.
