### ISSUE TITLE
Error after (pip) installation

### ISSUE THREAD

**Issue by jnaor** [qcr/gtsam-quadrics#21]
Hi,

After installing using 
1. pip3 install gtsam
2. pip3 install gtsam_quadrics

I get the following errors on the example code on the github page:

```
pose_key = int(gtsam.symbol(ord('x'), 0))
```
results in:
```
TypeError: symbol(): incompatible function arguments. The following argument types are supported:
    1. (chr: str, index: int) -> int
```

After removing the ord() I get another error:

`bbox_noise = gtsam.noiseModel_Diagonal.Sigmas(np.array([10]*4, dtype=np.float))
`
results in 

`AttributeError: module 'gtsam' has no attribute 'noiseModel_Diagonal'
`

Replacing noiseModel_Diagonal with noiseModel.Diagonal, I get one more error:

`graph.add(bbf)
`
which results in 
```

TypeError: add(): incompatible function arguments. The following argument types are supported:
    1. (self: gtsam.gtsam.NonlinearFactorGraph, factor: gtsam::NonlinearFactor) -> None
```

I'd be grateful for your help.

**Comment by btalb** [comment]
Thanks for posting @jnaor .

Sorry about the delay, this codebase is in a bit of a migration phase that should be finished in the next week or so.

The examples were still using the GTSAM API from before 4.1. This library has been upgraded to use 4.1, and the examples have been moved to our [QuadricSLAM repository](https://github.com/qcr/quadricslam) which is not quite finished yet. There are some demonstrations of working code in there already though if that's helpful.

As for your specific errors:
- `gtsam.symbol()` now takes a char not int, as you've found with your fix of removing the `ord()` call
- the latest version of this library should've removed the last error ("incompatible function arguments")

Let me know if you face anymore issues.
