### ISSUE TITLE
When using gtsam build with this repository it gives Point2 attribute not found

### ISSUE THREAD

**Issue by dishank-b** [qcr/gtsam-quadrics#8]
`p = gtsam.Point2()` gives error and says `gtsam doesn't containt the attribute Point2`.

**Comment by lachlan-nicholson** [comment]
This is likely an indication that the gtsam library has not been correctly installed. Is this still an issue?

**Comment by dishank-b** [comment]
Yeah it's something with gtsam imported with this repository. I used independently build gtsam and it works.

**Comment by btalb** [comment]
Sorry about the delay @dishank-b; looking into this now.

This seems to be upstream, as the `Point2` and `Point3` classes are both still missing when trying to build `4.1.1` in isolation.

I've posted this issue borglab/gtsam#1242 and will work on a resolution from there.

Do you have any details on the independtly built `gtsam` you had that works? Was it 4.1 or an older version?

**Comment by btalb** [comment]
Have identified this is an issue with us not including the Python shims from the GTSAM project; will work on rectifying for next release.

**Comment by btalb** [comment]
Should now be fixed. Upgrade to v0.2.2.
